/* DAKboard Sports — live schedule/results display */
const TEAMS={reds:{label:"Reds",logo:"logos/Reds.PNG",kind:"pro"},bengals:{label:"Bengals",logo:"logos/Bengals.PNG",kind:"pro"},fcc:{label:"FCC",logo:"logos/FCC.PNG",kind:"pro"},louisville:{label:"Louisville",logo:"logos/Louisville.png",kind:"college"}};
const FEEDS=[{team:"reds",sport:"baseball",league:"mlb",id:"17",label:""},{team:"bengals",sport:"football",league:"nfl",id:"4",label:""},{team:"fcc",sport:"soccer",league:"usa.1",id:"18267",label:""},{team:"louisville",sport:"football",league:"college-football",id:"97",label:"Football"},{team:"louisville",sport:"basketball",league:"mens-college-basketball",id:"97",label:"MBB"},{team:"louisville",sport:"basketball",league:"womens-college-basketball",id:"97",label:"WBB"},{team:"louisville",sport:"volleyball",league:"womens-college-volleyball",id:"97",label:"Volleyball"},{team:"louisville",sport:"baseball",league:"college-baseball",id:"97",label:"Baseball"}];
const feedErrors=[];
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function localDateKey(d){return `${d.getFullYear()}${String(d.getMonth()+1).padStart(2,"0")}${String(d.getDate()).padStart(2,"0")}`}
function dayKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function scoreOf(c){const r=c?.score;if(r!==undefined&&r!==null&&r!==""){if(typeof r==="object")return String(r.displayValue??r.value??"");return String(r)}return c?.displayValue!==undefined?String(c.displayValue):""}
function numericScore(v){if(v==="")return null;const n=Number(v);return Number.isFinite(n)?n:null}
function normalizeEvent(e,f){const c=e.competitions?.[0];if(!c)return null;const cs=c.competitors||[],t=cs.find(x=>String(x.team?.id)===String(f.id));if(!t)return null;const oe=cs.find(x=>x!==t),o=oe?.team||{},type=(c.status||e.status||{}).type||{},completed=Boolean(type.completed),canceled=type.name==="STATUS_CANCELED",postponed=type.name==="STATUS_POSTPONED",date=new Date(e.date||c.date);if(Number.isNaN(date.getTime()))return null;const ts=scoreOf(t),os=scoreOf(oe),a=numericScore(ts),b=numericScore(os);let result="";if(completed&&a!==null&&b!==null)result=a>b?"W":a<b?"L":"T";else if(completed&&t.winner===true)result="W";else if(completed&&oe?.winner===true)result="L";return{id:`${f.team}-${f.sport}-${e.id}`,team:f.team,sport:f.label||"",opponent:o.shortDisplayName||o.displayName||o.name||"Opponent",home:t.homeAway==="home",date,dateKey:dayKey(date),status:completed?"final":canceled?"canceled":postponed?"postponed":"scheduled",result,targetScore:ts,opponentScore:os,time:canceled?"Canceled":postponed?"Postponed":completed?"Final":date.toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}}
async function fetchFeed(f,start,end){const url=`https://site.api.espn.com/apis/site/v2/sports/${f.sport}/${f.league}/teams/${f.id}/schedule?dates=${localDateKey(start)}-${localDateKey(end)}`,r=await fetch(url,{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();return(d.events||[]).map(e=>normalizeEvent(e,f)).filter(Boolean)}
async function loadGames(){feedErrors.length=0;const today=new Date(),start=new Date(today.getFullYear(),today.getMonth(),today.getDate()-1),end=new Date(today.getFullYear(),today.getMonth(),today.getDate()+3,23,59,59,999),results=await Promise.all(FEEDS.map(async f=>{try{return await fetchFeed(f,start,end)}catch(e){feedErrors.push(`${f.team}/${f.label||f.sport}: ${e.message}`);return[]}})),unique=[...new Map(results.flat().filter(g=>g.date>=start&&g.date<=end).map(g=>[g.id,g])).values()];unique.sort((a,b)=>a.date-b.date);const dates=Array.from({length:5},(_,i)=>new Date(today.getFullYear(),today.getMonth(),today.getDate()+i-1));return dates.map((d,i)=>({date:d,games:unique.filter(g=>g.dateKey===dayKey(d)&&(i!==0||g.status==="final"))}));}
function dateTitle(d,i){if(i===0)return "Yesterday";if(i===1)return "Today";if(i===2)return "Tomorrow";return d.toLocaleDateString([], {weekday:"long",month:"numeric",day:"numeric"});}
function gameRow(g){const team=TEAMS[g.team];const label=team?.kind==="college"?`<span class="sport">${esc(g.sport)}</span>`:"";let right=esc(g.time||"");if(g.status==="final"){const cls=g.result==="W"?"win":g.result==="L"?"loss":"draw",score=g.targetScore!==""&&g.opponentScore!==""?`${g.targetScore}–${g.opponentScore}`:"Score unavailable";right=`<span class="result ${cls}">${esc(g.result||"FINAL")} ${esc(score)}</span>`}const teamDisplay=team?.kind==="college"?`<span class="team-name">${esc(team.label)}</span>`:"";return`<article class="game"><div class="logo"><img src="${esc(team?.logo||"")}" alt=""></div><div class="details"><div class="team-line">${teamDisplay}${label}<span class="opponent-inline">${g.home?"vs":"@"} ${esc(g.opponent)}</span></div></div><div class="time">${right}</div></article>`}
function renderSection(title,games){return games.length?`<section class="day"><h2 class="day-title">${esc(title)}</h2>${games.map(gameRow).join("")}</section>`:""}
function render(days){const c=document.getElementById("sports"),s=days.map((d,i)=>renderSection(dateTitle(d.date,i),d.games));if(feedErrors.length)s.push(`<section class="day diagnostics"><h2 class="day-title">Feed diagnostics</h2><div class="error">${feedErrors.map(esc).join("<br>")}</div></section>`);c.innerHTML=s.filter(Boolean).join("")||`<div class="empty">No games scheduled.</div>`;document.getElementById("updated").textContent="BUILD D82F6A4"}
async function refresh(){try{render(await loadGames())}catch(e){console.error(e);document.getElementById("sports").innerHTML=`<div class="error">Sports data temporarily unavailable.</div>`}}refresh();setInterval(refresh,15*60*1000);
